const formato = {
  id: 1,
  startTime: 7,
  time: 1,
  day: 'lunes',
  show: true,
  backgroundColor: '#ff0000',
  color: '#ffffff',
  data: {
    name: 'Curso 1',
    codigo: 'A',
    profesor: 'Profesor 1',
    type: 'Laboratorio',
    group: 'Grupo 1',
  },
};
let initialHorary = {
  heightCourse: '4rem',
  firstHour: '7',
  lastHour: '22',
  weekdays: [
    'Lunes',
    'Martes',
    'Miercoles',
    'Jueves',
    'Viernes',
    'Sabado',
    'Domingo',
  ],
  courses: [
    {
      id: 1,
      startTime: 7,
      time: 1,
      day: 'lunes',
      show: true,
      backgroundColor: '#ff0000',
      color: '#ffffff',
      data: {
        name: 'Curso 1',
        codigo: 'A',
        profesor: 'Profesor 1',
        type: 'Laboratorio',
        group: 'Grupo 1',
      },
    },
    {
      id: 2,
      startTime: 7,
      time: 1,
      day: 'martes',
      show: true,
      backgroundColor: '#ff0000',
      color: '#ffffff',
      data: {
        name: 'Curso 1',
        codigo: 'A',
        profesor: 'Profesor 1',
        type: 'Laboratorio',
        group: 'Grupo 1',
      },
    },
    {
      id: 3,
      startTime: 7,
      time: 1,
      day: 'miercoles',
      show: true,
      backgroundColor: '#ff0000',
      color: '#ffffff',
      data: {
        name: 'Curso 1',
        codigo: 'A',
        profesor: 'Profesor 1',
        type: 'Laboratorio',
        group: 'Grupo 1',
      },
    },
    {
      id: 4,
      startTime: 7,
      time: 1,
      day: 'jueves',
      show: true,
      backgroundColor: '#ff0000',
      color: '#ffffff',
      data: {
        name: 'Curso 1',
        codigo: 'A',
        profesor: 'Profesor 1',
        type: 'Laboratorio',
        group: 'Grupo 1',
      },
    },
    {
      id: 5,
      startTime: 7,
      time: 1,
      day: 'viernes',
      show: true,
      backgroundColor: '#ff0000',
      color: '#ffffff',
      data: {
        name: 'Curso 1',
        codigo: 'A',
        profesor: 'Profesor 1',
        type: 'Laboratorio',
        group: 'Grupo 1',
      },
    },
  ],
};
